// {
//   "name": "portfolio",
//   "version": "0.1.0",
//   "private": true,
//   "scripts": {
//     "dev": "next dev",
//     "build": "next build",
//     "start": "next start",
//     "lint": "next lint",
//     "deploy": "vercel --prod"
//   },
//   "dependencies": {
//     "@gsap/react": "^2.1.1",
//     "@react-three/drei": "^9.112.1",
//     "@react-three/fiber": "^8.16.2",
//     "@sentry/nextjs": "^7.105.0",
//     "@tabler/icons-react": "^3.1.0",
//     "@types/three": "^0.163.0",
//     "class-variance-authority": "^0.7.0",
//     "clsx": "^2.1.0",
//     "dotenv": "^16.4.5",
//     "framer-motion": "^11.0.25",
//     "gsap": "^3.12.5",
//     "gsap-trial": "^3.12.5",
//     "locomotive-scroll": "^4.1.4",
//     "lucide-react": "^0.365.0",
//     "mini-svg-data-uri": "^1.4.4",
//     "next": "14.1.4",
//     "next-themes": "^0.3.0",
//     "nodemailer": "^6.9.15",
//     "react": "^18",
//     "react-dom": "^18",
//     "react-icons": "^5.0.1",
//     "react-lottie": "^1.2.4",
//     "sass": "^1.78.0",
//     "scrolltrigger": "^1.0.1",
//     "sweetalert2": "^11.14.0",
//     "tailwind-merge": "^2.2.2",
//     "tailwindcss-animate": "^1.0.7",
//     "three": "^0.163.0",
//     "three-globe": "^2.31.0",
//     "vercel": "^32.3.0"
//   },
//   "devDependencies": {
//     "@types/locomotive-scroll": "^4.1.3",
//     "@types/node": "^20",
//     "@types/nodemailer": "^6.4.15",
//     "@types/react": "^18",
//     "@types/react-dom": "^18",
//     "@types/react-lottie": "^1.2.10",
//     "autoprefixer": "^10.0.1",
//     "eslint": "^8",
//     "eslint-config-next": "14.1.4",
//     "postcss": "^8",
//     "tailwindcss": "^3.3.0",
//     "typescript": "^5"
//   }
// }